import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="flex w-full items-center justify-center gap-6 px-4 pt-2">
        <Link href={"/"}>Home</Link>
        <Link href={"/availability"}>Availability</Link>
        <Link href={"/balancemovement"}>Balance Movement</Link>
        <Link href={"/gangguan"}>Gangguan</Link>
        <Link href={"/perawatan"}>Perawatan</Link>
        <Link href={"/saldogudang"}>Saldo Gudang</Link>
      </header>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
